# Generated by Django 3.1.4 on 2020-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True)),
                ('new_total', models.IntegerField(default=0)),
                ('old_total', models.IntegerField(default=0)),
                ('recommended', models.BooleanField(default=False)),
                ('cover', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
