FROM python:3
ENV PYTHONUNBUFFERED=1

ENV HOME=/home/code
WORKDIR /code/hechuang
SHELL [ "/bin/bash", "-c" ]

RUN mkdir -p /home/code
RUN mkdir -p /code/hechuang

# Install packages
COPY ./requirements.txt /code
RUN pip install pip -U
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple
RUN pip install -r /code/requirements.txt

# Prepare to use non-root
## root:mypasswd
## code:mypasswd
RUN echo 'root:mypasswd' | chpasswd
COPY ./webscript/ /code/script/
RUN echo "xxx"
RUN chmod +x /code/script/entrypoint.sh
ENTRYPOINT [ "/code/script/entrypoint.sh" ]
CMD []