# Generated by Django 3.1.4 on 2020-12-29 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleRequest',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='order.order')),
                ('message', models.TextField(blank=True)),
                ('price', models.IntegerField(default=0)),
                ('allowed', models.BooleanField(null=True)),
                ('read', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
    ]
