# Generated by Django 3.1.4 on 2020-12-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_email', models.EmailField(default='1753764@tongji.edu.cn', max_length=254, verbose_name='出版商的邮箱')),
                ('discount_rate', models.FloatField(default=0, verbose_name='折扣率')),
                ('old_rate', models.FloatField(default=0.3, verbose_name='折旧折扣率')),
                ('recycle_rate', models.FloatField(default=0.7, verbose_name='回收折扣率')),
                ('address', models.TextField(default='同济大学', verbose_name='地址')),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
